### ISSUE TITLE
QUEUE=message php vendor/bin/resque

### ISSUE THREAD

**Issue by gangming** [resque/php-resque#14]
Hi,all
in command line ,I run QUEUE=message php vendor/bin/resque;then I push many task into queue .but only one queue was execute.others also in queue.not execute.
anyone can help me ?

os: darwin Kernel Version 18.2.0

**Comment by danhunsaker** [comment]
To clarify, by "only one queue was execute[d]", do you mean queue, or job?

**Comment by danhunsaker** [comment]
Ok. Which version are you using, and how did you install it?

**Comment by gangming** [comment]
"version": "v1.3.3". installed by composer

**Comment by gangming** [comment]
"version": "v1.3.3". installed by composer

**Comment by gangming** [comment]
I resolved this question , the command `QUEUE=message php vendor/bin/resque` I run by supervisord. then config `autorestart=unexpected   exitcodes=0`.
