### ISSUE TITLE
Move "ext-pcntl" from "require" to "suggest"

### ISSUE THREAD

**Issue by danhunsaker** [resque/php-resque#2]
> slince commented on Sep 13, 2017:
> 
> I can't install it via composer on windows.

(from danhunsaker/php-resque-archive#7)

**Comment by danhunsaker** [comment]
This is completed on the `develop` branch and `v1.3.5-beta`.

**Comment by Madeorsk** [comment]
php-resque did not work because pcntl was not enabled (SIGTERM constant was unknown). If pcntl is required, indicate it in composer.json is clearer.

**Comment by danhunsaker** [comment]
If the Composer config supported platform-specific requires, we'd use that to ignore this extension completely, but it's not _quite_ that smart. So the best we can do is suggest it.
