### ISSUE TITLE
Redis password extracted from DSN are not url-decoded

### ISSUE THREAD

**Issue by ghost** [resque/php-resque#21]
## Expected Behavior

The password extracted from a Redis DSN should be url-decoded.

## Current Behavior

The password extracted from a Redis DSN is not url-decoded.

## Possible Solution

Use `urldecode()` to decode the password before passing it to redis.

### Try 1:
1. Use a password which looks like this: `abc@#!`
2. Try to pass it into `\Resque::setBackend()`
    ```php
    \Resque::setBackend('redis://x:abc@#!@127.0.0.1:6379/1');
    ```
3. It won't work. The `parse_url()` function used in `Resque_Redis::parseDsn()` does not recognize this as a correct URL.

### Try 2:
1. Same password as above but encoded before passing it to `\Resque::setBackend()`
    ```php
    \Resque::setBackend('redis://x:abc%40%23!@127.0.0.1:6379/1');
    ```
2. It won't work. The encoded password are passed to the redis backend, resulting in an invalid password exception.

## Context

Passwords can contain special characters like `:@/`. In URL these characters must be encoded.

## My Environment

* PHP-Resque version: v1.3.3
* PHP version: 5.6.40
* Redis version: 5.0.3
* Server type and version: 
* Operating System and version: Arch GNU/Linux (linux 4.19.26)

**Comment by jchoi926** [comment]
Seems to be specifically the # character.
https://bugs.php.net/bug.php?id=73754

Possible to add urldecode to the url parts?

**Comment by sergeyklay** [comment]
IMO better way is to provide a strategy for the decoder:

- `redis://<USER>:<PASSWORD>@<HOST>:<PORT>/<DB>?password-hashing=<strategy>`:

and `strategy` may be `B` (base64), `U` (url_encode), etc

**Comment by emipac** [comment]
Is it possible to connect only with password, without a user? Does <PASSWORD>@<HOST>:<PORT> work?

**Comment by danhunsaker** [comment]
> Is it possible to connect only with password, without a user? Does PASSWORD@HOST:PORT work?

It isn't possible, no. This is a limitation of the URI spec, rather than PHP, Redis, or Resque. That said, `:PASSWORD@HOST:PORT` should work just fine.

> IMO better way is to provide a strategy for the decoder:
> 
> * `redis://<USER>:<PASSWORD>@<HOST>:<PORT>/<DB>?password-hashing=<strategy>`:
> 
> and `strategy` may be `B` (base64), `U` (url_encode), etc

This approach looks pretty viable. I'm not sure we'd want to support _too_ many encoding strategies, but `b` and `u` seem reasonable to support both of, with the default being neither.

**Comment by JohnPremKumar** [comment]
I have added those password encoding as @sergeyklay suggested. Can anyone anyone check and merge it  #35

**Comment by danhunsaker** [comment]
This has been merged!
