### ISSUE TITLE
InvalidArgumentException when installing through composer

### ISSUE THREAD

**Issue by oniramarf** [resque/php-resque#22]
### My question:
I'm having an issue while installing php-resque on a machine through composer. The only error message that is thrown is:

```
[InvalidArgumentException]                                                                  
  $from (/path/to/my/project/vendor/bin/resque) and $to () must be absolute paths.
```

Also, if I remove resque/php-resque from composer.json, all the other dependecies are correctly installed.

## My Environment
* PHP-Resque version: 1.3.3
* PHP version: 5.5.9-1ubuntu4.29 (cli) (built: Apr 22 2019 18:33:52)
* Composer version: 1.8.5 2019-04-09 17:46:47
* Operating System and version: Ubuntu 14.04.6 LTS

**Comment by danhunsaker** [comment]
This is certainly odd. I've never seen this particular error before. It looks like something is broken within Composer itself, though, since we only tell it (in `composer.json`) what files to link into `vendor/bin` relative to the package itself. Are you still experiencing this one?
