### ISSUE TITLE
PHP 7.2 to 7.4 compatibility ?

### ISSUE THREAD

**Issue by Benoit-amo** [resque/php-resque#23]
Does PHP Resque works on PHP 7.2, 7.3 and 7.4 ?

We are upgrading an old PHP 5 app, which using the original version of PHP Resque, and we need to know if we can keep using it with recent versions of PHP.

Could you update the Travis config so we can see the tests results ?

**Comment by danhunsaker** [comment]
Are you looking at https://travis-ci.org/resque/php-resque ? Travis doesn't support PHP 7.4 testing, just yet, but tests have been run for 7.2 and 7.3 for a while, now.

**Comment by Benoit-amo** [comment]
Ok sorry, I missed that. I was looking on master.
And thank you for the commit 25ff30789091b9b3d0eb7a0bb2a860f04f53c49d about the 7.4!
