### ISSUE TITLE
Queuing a closure

### ISSUE THREAD

**Issue by atefBB** [resque/php-resque#24]
### My question:
I'm facing prob with queuing `closure`, have you an idea how to do it?

## My Environment

* PHP-Resque version: v1.3.3
* PHP version: PHP 7.2.20-1+ubuntu16.04.1+deb.sury.org+1
* Redis version:  5.0.5 (dockerized)
* Server type and version: I don't know.
* Operating System and version: ubuntu

**Comment by danhunsaker** [comment]
Since `Closure` doesn't `implements Resque_JobInterface`, it can't be queued directly. Additionally, a `Closure` can't be serialized, so it can't be stored in the queue in a way the workers can retrieve and process.

You'll need to create a job class.

**Comment by atefBB** [comment]
Thx for the explanation @danhunsaker !
