### ISSUE TITLE
Possibility of multiple concurrent workers fetching same job

### ISSUE THREAD

**Issue by aravind-zrx** [resque/php-resque#25]
### My question:
 Is there a possibility of fetching and processing same job while multiple concurrent workers are in place?

## My Environment

* PHP-Resque version:
* PHP version:
* Redis version:
* Server type and version:
* Operating System and version:

**Comment by danhunsaker** [comment]
Not with the way we use Redis lists, no. Jobs are reserved for work by removing them from the list entirely, and Redis only allows one action at a time, so no two workers will ever get the same job at once.
