### ISSUE TITLE
in demo of resque is not working . it is not picking class name 

### ISSUE THREAD

**Issue by Abhishek-Ml** [resque/php-resque#27]
getting class not found error 
```
[notice] Starting work on (Job{default} | ID: f8c29eab8d18d1a3933d0284eee95145 | My_Job | [{"name":"Chris"}])
[critical] (Job{default} | ID: f8c29eab8d18d1a3933d0284eee95145 | My_Job | [{"name":"Chris"}]) has failed Resque_Exception: Could not find job class My_Job. in /var/www/php-resque/lib/Resque/Job/Factory.php:17
Stack trace:
#0 /var/www/php-resque/lib/Resque/Job.php(172): Resque_Job_Factory->create('My_Job', Array, 'default')
#1 /var/www/php-resque/lib/Resque/Job.php(189): Resque_Job->getInstance()
#2 /var/www/php-resque/lib/Resque/Worker.php(255): Resque_Job->perform()
#3 /var/www/php-resque/lib/Resque/Worker.php(207): Resque_Worker->perform(Object(Resque_Job))
#4 /var/www/php-resque/bin/resque(185): Resque_Worker->work(5, false)
#5 {main}
```

my job class file 
```
<?php
class My_Job
{
    public function setUp()
    {
      Resque::setBackend('localhost:6379'); 
    }

    public function perform()
    {
        file_put_contents("/var/www/php-resque/demo/mytxt1.txt",'tesddsadasdst');
         // file_put_contents("mytxt.txt",'test');

    }

    public function tearDown()
    {
        // ... Remove environment for this job
    }
}
```

* PHP-Resque version: 
* PHP version: 7
* Redis version:
* Server type and version:
* Operating System and version:

**Comment by Abhishek-Ml** [comment]
tryied removing underscore and namespaces also but still facing same issue

**Comment by danhunsaker** [comment]
The worker process is entirely separate from the process that queues up the job, so if you're loading `My_Job` in manually (via `include()` or `require()` or their `*_once()` variants), you need to make sure you load it in your worker process as well. Generally, we recommend Composer for this, as it provides autoloading of class files, but you can use the `APP_INCLUDE` environment variable instead if you prefer. (So something like `APP_INCLUDE=../jobs/my_job.php php bin/resque` when you start the worker process.)
