### ISSUE TITLE
How to manage workers

### ISSUE THREAD

**Issue by JoyceBabu** [resque/php-resque#29]
What is the recommended method for managing the workers? I have been using https://github.com/ebernhardson/php-resque-pool for managing the queues, but the project has not been updated for a few years now.

**Comment by danhunsaker** [comment]
Neither had PHP Resque itself, to be fair. I'd continue using it for now, and I'll try to get in touch with its creator about maintenance.

**Comment by JoyceBabu** [comment]
Is it possible to manage the workers with `systemd`? Would you mind sharing how you manage it?

**Comment by danhunsaker** [comment]
I use a project called Nanobox to handle a lot of devops stuff for me, so I just start each command directly using its format. I'm afraid I won't be much help here.

**Comment by JoyceBabu** [comment]
Thank you for the information.

**Comment by mfn** [comment]
Though probably not very helpful here, I do like how [Laravel Horizon](https://laravel.com/docs/6.x/horizon) did iron this out:
- you've one PHP "supervisor" process
- spawns a "master" for each queue
- which in turns is responsible for managing all the "worker" for each queue

Only the PHP "supervisor" process needs to be managed (i.e. via supervisord) and everything else is handled via configuration file (i.e. which queues, amount of workers per queue, per queue-worker configuration).

This design always works i.e. gracefully stopping the PHP "supervisor" will not kill workers immediately, they can finish their job, etc.

**Comment by danhunsaker** [comment]
@mfn - That's essentially what php-resque-pool does, though with one fewer layers of forking.

**Comment by JoyceBabu** [comment]
@danhunsaker I had sent a few PRs to ebernhardson/php-resque-pool. You had approved them, but the PRs were not merged. Can you please give it another look?

**Comment by danhunsaker** [comment]
I unfortunately don't have access to that repo for merges.

**Comment by JoyceBabu** [comment]
I have pinged @ebernhardson directly on the PR.
