### ISSUE TITLE
Running under Docker in Kubernetes environment

### ISSUE THREAD

**Issue by RVN-BR** [resque/php-resque#3]
Hi, I'd like to know if others are having success running php-resque in docker containers in a kubernetes environment.

I can share dockerfile/startup script if anyone is interested although its pretty standard.

One thing I cant get past is only 1 worker per container... this "makes sense" from a docker perspective but makes the workers more resource hungry than "legacy" workers...

I also notice that after a long time some job queues consistently fail with dirty 255 exceptions.  I *believe* these are jobs erroring due to oom errors, but I havent been able to pinpoint it 100%... I know this specific queue is resource intensive (esp cpu hungry on "traditional" workers).

The main idea for this issue is to share experiences and best practices... Currently looking for an elegant way to restart the queue runner every X time or X processes, or something.

**Comment by danhunsaker** [comment]
I don't see any problem with `COUNT=3` or similar with a Docker container, personally. The Docker Way™ is generally applied overly strictly without good reason. The point is to prevent running too many of the same processes across a single system - if every PHP container runs its own MySQL, you can only run a small handful of them at a time. More than one of the same process in a container is perfectly acceptable, and is frequently done with Docker's own official images.

255s are hard to track down, yeah. They are generally caused by OOM or segfault, but unless you have an extension in play that regularly segfaults, OOM is far more likely.

There have been a handful of "restart worker after X condition" PRs at the old repo. Most of them aren't mergeable anymore, so will need to be reworked to the current codebase, but I'd be all for merging them in.

**Comment by RVN-BR** [comment]
Hi Dan, thanks for the input... huh thats strange... whenever I try anything above 1 it seems to spawn and then quits immediately... I share your view abt The Docker Way™  ;)

`resque-worker_1   | #!/usr/bin/env php
resque-worker_1   | [notice] [21:08:34 2018-12-04] Starting worker f523e50a8ee8:197:default_Pro
resque-worker_1   | [debug] [21:08:34 2018-12-04] Registered signals
resque-worker_1   | [notice] [21:08:34 2018-12-04] Starting worker f523e50a8ee8:198:default_Pro
resque-worker_1   | [debug] [21:08:34 2018-12-04] Registered signals
resque-worker_1   | ps: bad -o argument 'command', supported arguments: user,group,comm,args,pid,ppid,pgid,etime,nice,rgroup,ruser,time,tty,vsz,sid,stat,rss
resque-worker_1   | ps: bad -o argument 'command', supported arguments: user,group,comm,args,pid,ppid,pgid,etime,nice,rgroup,ruser,time,tty,vsz,sid,stat,rss
kubernetes-images_resque-worker_1 exited with code 0`

with 1:

`resque-worker_1   | #!/usr/bin/env php
resque-worker_1   | [notice] [21:09:50 2018-12-04] Starting worker cc3e5fe8316a:1:default
resque-worker_1   | [debug] [21:09:50 2018-12-04] Registered signals
resque-worker_1   | ps: bad -o argument 'command', supported arguments: user,group,comm,args,pid,ppid,pgid,etime,nice,rgroup,ruser,time,tty,vsz,sid,stat,rss
resque-worker_1   | [info] [21:09:50 2018-12-04] Checking default for jobs
resque-worker_1   | [info] [21:09:50 2018-12-04] Sleeping for 2`

Would you mind sharing a bit of your setup? startup scripts and such? Although what I'm running is pretty vanilla afaict...

**Comment by sergeyklay** [comment]
@RVN-BR 

> ps: bad -o argument 'command', supported arguments: ...

Did you see https://github.com/gliderlabs/docker-alpine/issues/173

**Comment by RVN-BR** [comment]
Thanks @sergeyklay ! I was trying all sorts of changes to the command itself!  I knew I had come across a fix!  (running to change the dockerfile!)

**Comment by danhunsaker** [comment]
Oh, hi, @sergeyklay! Didn't know I'd find you here, too!

@RVN-BR We really ought to adjust the code in the library itself to not rely on a specific `ps` in the first place. But! Good to have a workaround.

As to `COUNT` > 1 .... I'll have to take a peek at the start script and make sure it's spawning children in the right way, still, I guess. The parent process is _supposed_ to stick around and monitor the children it spawns, meaning you have `COUNT` worker processes, and a parent monitoring process that respawns dead children.

**Comment by RVN-BR** [comment]
@danhunsaker Yeah, it doesnt really make sense why the parent process sticks around with COUNT=1 and wouldnt with COUNT>1.... I'll try to see if I find something too

**Comment by RVN-BR** [comment]
I'm going to close this, as somehow it stopped happening...  Its now working correctly with multiple workers... go figure...
