### ISSUE TITLE
task execute interval is slow and too long

### ISSUE THREAD

**Issue by juicechu** [resque/php-resque#30]
task execute interval is slow and too long

## Expected Behavior
i think sleep 50ms is good for it

## Current Behavior
https://github.com/resque/php-resque/blob/7dd1474f73d5f2a4356cb2f69bd403476606c16e/lib/Resque/Worker.php#L266
![image](https://user-images.githubusercontent.com/5253183/71538755-9d913480-296b-11ea-840b-84143bea9a36.png)

## Possible Solution
change the pcntl_wait sleep time，or support extra config control it

**Comment by Redominus** [comment]
There is already a INTERVAL enviroment variable. At this moment you even can setup a float value to achieve the sleep you want as data type is just typehinted. 
```bash
INTERVAL=0.5 php vendor/bin/resque
