### ISSUE TITLE
Any chance of bringing over the port of php-resque-scheduler?

### ISSUE THREAD

**Issue by roynasser** [resque/php-resque#4]
Dont mean to hog the issues, nor to be pushy lol... But would it be fair to suggest to bring over php-resque-scheduler into this repo as well? 

We use it in production, and even if it isnt maintained, the composer package requires chrisboulton/php-resque... Before I go trying to hack around I thought I'd ask?

I assume some others may be in a similar position too... Thanks for bringing this over!  I hope we can contribute too in due time!

**Comment by danhunsaker** [comment]
I'd like to bring over that and possibly some others, at some point. I don't, however, have permissions to create repos in the `resque` namespace, so it's something which will be a process to make happen. Forks are pretty much your best bet at the moment, sadly.

**Comment by pprkut** [comment]
Chris mentioned in https://github.com/chrisboulton/php-resque/issues/248 that he wanted to merge php-resque-scheduler in. That would be another option

**Comment by danhunsaker** [comment]
That's fair, but also even more of a process. PRs welcome, of course!

**Comment by skaos** [comment]
Yes, i would like to see the port too!
Thanks for your work guys!

**Comment by danhunsaker** [comment]
This is done via PR #19, which is merged into `develop` and `v1.3.5-beta`.
