### ISSUE TITLE
Resque scan parameters are not as expected

### ISSUE THREAD

**Issue by phpxianyu** [resque/php-resque#41]
### My question:

The return value of 'scan' in 'redis' is a cursor and an array,' scan 'in' resque 'is an array, What do you suggest
In the case of redis
```js
127.0.0.1:6379[7]> scan 0 match worker:job:* count 100
1) "0"
2) 1) "worker:job:backend\\modules\\job\\resque:10"
    2) "worker:job:backend\\modules\\job\\resque:20"
```
In the case of php-resque
```js
$resqueList = Resque::redis()->scan($cursor,'worker:job:*',"100");
return $resqueList;
```
The return values are as follows
```js
[
"worker:job:backend\modules\job\resque:10",
"worker:job:backend\modules\job\resque:20"
]
```

## My Environment

* PHP-Resque version: 
* PHP version: 7.1.32
* Redis version: 4.2.0
* Server type and version:
* Operating System and version:

**Comment by phpxianyu** [comment]
@danhunsaker

**Comment by danhunsaker** [comment]
The current version of PHP Resque uses an older version of Credis as its interface with Redis. Credis predates the `scan` command by a few years, so it doesn't support `scan` at all. You're better off using a full, up-to-date Redis library if you want to access Redis directly; PHP Resque isn't intended to be used as a general-purpose Redis library.
