### ISSUE TITLE
Job dependencies

### ISSUE THREAD

**Issue by PommeVerte** [resque/php-resque#45]
Hello,

Does `php-resque` support job dependencies? I would basically like to carry out a task that involves jobs A, B, C, and D.  B+C depend on A being done. And D depends on B+C being done. 
Is this supported out of the box? I couldn't see anything in the documentation but maybe I'm missing it. 

Thanks!

**Comment by magussiro** [comment]
you can design your self by a class pipeline with FSM

**Comment by PommeVerte** [comment]
Thanks
