### ISSUE TITLE
Define goals/roadmap

### ISSUE THREAD

**Issue by mfn** [resque/php-resque#9]
I think it would help to community to get some idea where this would be going.

The codebase has a good and strong history, OTOH it also references software which is also very old (see composer.json: PHP 5.3, PHPUnit 3.* but not the PHP version isn't covered in travis for example.

What are some plans/ideas regarding:
- Codestyle
- Namespaces
- PHP Support (7.0 is EOL)
- Features (scheduler? plugins?)
- resque-compatibility
- …

**Comment by danhunsaker** [comment]
https://github.com/resque/php-resque/projects

**Comment by mfn** [comment]
> https://github.com/resque/php-resque/projects

lol, fair enough; haven't yet gotten used to this "new" feature 👍 

> That's why I've set some stuff up in the Projects tab to track both what we want to do on a high level, and what issues/PRs exist to track making it happen.

Do you already have an idea how/when to do it?

These steps surely will be a hard break for anyone. The way I understand it, right now, it's a drop-in replacement as it still uses all the same conventions but every refactoring => 💥 

Does it make sense to even promote it in the current form?

PS: just ideas/having some questions => I really like this is getting some fresh air here 👍

**Comment by rajibahmed** [comment]
@danhunsaker created a slack for php-resque https://join.slack.com/t/php-resque/shared_invite/enQtNTE3MTkwOTkwMzg0LWVlNTFkZTBhMjI3NjA4Yzk3YzUxZDZkNDczMTA4OTE4NmY0NmZlYzQ2ZjJjZWRlM2M1YzZkNDIwNGNlNjgyZTE

**Comment by mfn** [comment]
@rajibahmed #fail, totally missed this notification!

The current master (also develop) even doesn't run tests on 7.4, released over a year ago.

@danhunsaker what's your current feel? What do you think is "the thing" missing to move forward?

I'm having a hard time contributing with still the "legacy stuff in the way" (sorry if this sounds negative, lack of better words here). Totally understand that resources / time is always an issue too ofc.

Thanks

**Comment by mfn** [comment]
Closing, as I'm no longer using resque
